// Cuisine hierarchy and tag relationships
const cuisineTagData = {
  // Geographical Tags & their Food Tags/Subpage Tags
  cuisines: [
    {
      id: 1,
      name: "Emirati",
      category: "Arabic",
      foodTags: [
        "Luqaimat",
        "Kebab",
        "Harees",
        "Grills",
        "Shawarma",
        "Homestyle Meals",
      ],
      subpageTags: ["Grills", "Shawarma"],
      region: "Middle East",
    },
    {
      id: 2,
      name: "Arabic",
      category: "Arabic",
      foodTags: [
        "Kebab",
        "Manakish",
        "Shawarma",
        "Falafel",
        "Arabic Sweets",
        "Kunafa",
      ],
      subpageTags: ["Shawarma", "Manakish", "Arabic Sweets"],
      region: "Middle East",
    },
    {
      id: 3,
      name: "Lebanese",
      category: "Arabic",
      foodTags: [
        "Manakish",
        "Falafel",
        "Kebab",
        "Arabic Sweets",
        "Hummus",
        "Tabbouleh",
      ],
      subpageTags: ["Manakish", "Falafel"],
      region: "Middle East",
    },
    {
      id: 4,
      name: "Egyptian",
      category: "Arabic",
      foodTags: [
        "Koshary",
        "Falafel",
        "Kebab",
        "Bread",
        "Salads",
        "Street Food",
      ],
      subpageTags: ["Koshary", "Falafel"],
      region: "Middle East",
    },
    {
      id: 5,
      name: "Syrian",
      category: "Arabic",
      foodTags: [
        "Shawarma",
        "Kebab",
        "Manakish",
        "Kunafa",
        "Falafel",
        "Grilled Meats",
      ],
      subpageTags: ["Shawarma", "Kunafa"],
      region: "Middle East",
    },
    {
      id: 6,
      name: "Jordanian",
      category: "Arabic",
      foodTags: ["Mansaf", "Kebab", "Falafel", "Bread", "Grills", "Salads"],
      subpageTags: ["Mansaf", "Grills"],
      region: "Middle East",
    },
    {
      id: 7,
      name: "Japanese",
      category: "Asian",
      foodTags: ["Sushi", "Ramen", "Dimsum", "Tempura", "Teriyaki", "Boba Tea"],
      subpageTags: ["Sushi", "Ramen"],
      region: "Asia",
    },
    {
      id: 8,
      name: "Thai",
      category: "Asian",
      foodTags: ["Pad Thai", "Curry", "Soup", "Noodles", "Rice", "Dumplings"],
      subpageTags: ["Pad Thai", "Curry"],
      region: "Asia",
    },
    {
      id: 9,
      name: "Chinese",
      category: "Asian",
      foodTags: [
        "Fried Rice",
        "Noodles",
        "Dimsum",
        "Wonton",
        "Spring Rolls",
        "Kung Pao Chicken",
      ],
      subpageTags: ["Dimsum", "Fried Rice"],
      region: "Asia",
    },
    {
      id: 10,
      name: "Vietnamese",
      category: "Asian",
      foodTags: [
        "Pho",
        "Banh Mi",
        "Spring Rolls",
        "Vermicelli",
        "Noodles",
        "Soup",
      ],
      subpageTags: ["Pho", "Banh Mi"],
      region: "Asia",
    },
    {
      id: 11,
      name: "Korean",
      category: "Asian",
      foodTags: [
        "Bibimbap",
        "Korean BBQ",
        "Kimchi",
        "Ramen",
        "Dumplings",
        "Rice Bowls",
      ],
      subpageTags: ["Bibimbap", "Korean BBQ"],
      region: "Asia",
    },
    {
      id: 12,
      name: "Filipino",
      category: "Asian",
      foodTags: [
        "Tapsilog",
        "Pancit",
        "Adobo",
        "Lumpia",
        "Rice",
        "Street Food",
      ],
      subpageTags: ["Tapsilog", "Pancit"],
      region: "Asia",
    },
    {
      id: 13,
      name: "North Indian",
      category: "Indian",
      foodTags: ["Biryani", "Kebab", "Naan", "Curry", "Chaat", "Tandoori"],
      subpageTags: ["Biryani", "Chaat"],
      region: "South Asia",
    },
    {
      id: 14,
      name: "South Indian",
      category: "Indian",
      foodTags: ["Dosa", "Idli", "Sambar", "Biryani", "Chaat", "Rice"],
      subpageTags: ["Dosa", "Idli"],
      region: "South Asia",
    },
    {
      id: 15,
      name: "Pakistani",
      category: "Pakistani",
      foodTags: ["Biryani", "Karahi", "Kebab", "Naan", "Chaat", "Handi"],
      subpageTags: ["Biryani", "Karahi"],
      region: "South Asia",
    },
    {
      id: 16,
      name: "Bengali",
      category: "Indian",
      foodTags: ["Biryani", "Fish Curry", "Rice", "Sweets", "Soup", "Hilsa"],
      subpageTags: ["Biryani", "Sweets"],
      region: "South Asia",
    },
    {
      id: 17,
      name: "Italian",
      category: "European",
      foodTags: [
        "Pizza",
        "Pasta",
        "Risotto",
        "Tiramisu",
        "Gelato",
        "Carbonara",
      ],
      subpageTags: ["Pizza", "Pasta"],
      region: "Europe",
    },
    {
      id: 18,
      name: "American",
      category: "American",
      foodTags: ["Burger", "Steak", "BBQ", "Donuts", "Shakes", "Wings"],
      subpageTags: ["Burger", "BBQ & Grill"],
      region: "North America",
    },
    {
      id: 19,
      name: "Mexican",
      category: "American",
      foodTags: [
        "Tacos",
        "Burritos",
        "Enchiladas",
        "Guacamole",
        "Salsa",
        "Quesadillas",
      ],
      subpageTags: ["Tacos", "Burritos"],
      region: "North America",
    },
    {
      id: 20,
      name: "Turkish",
      category: "Arabic",
      foodTags: [
        "Doner",
        "Kebab",
        "Baklava",
        "Pide",
        "Mezze",
        "Turkish Coffee",
      ],
      subpageTags: ["Doner", "Kebab"],
      region: "Middle East",
    },
  ],

  // All available tags (from active_tags.csv)
  allTags: [
    // Arabic cuisine tags
    { id: 596, name: "Arabic", category: "Arabic" },
    { id: 426, name: "Arabic Coffee", category: "Arabic" },
    { id: 907, name: "Arabic Sweets", category: "Arabic" },
    { id: 1548, name: "Atayef", category: "Arabic" },
    { id: 1106, name: "Biryani", category: "Indian" },
    { id: 541, name: "BBQ & Grill", category: "General" },

    // Asian cuisine tags
    { id: 815, name: "Asian", category: "Asian" },
    { id: 1142, name: "Dimsum", category: "Asian" },
    { id: 1153, name: "Bibimbap", category: "Asian" },
    { id: 685, name: "Bubble Tea", category: "Asian" },
    { id: 1072, name: "Chaat", category: "Asian" },

    // General tags
    { id: 124, name: "Breakfast", category: "General" },
    { id: 211, name: "Bakery", category: "General" },
    { id: 250, name: "Coffee", category: "General" },
    { id: 53, name: "Burger", category: "General" },
    { id: 1217, name: "Cheat Meal", category: "General" },
    { id: 1232, name: "Best Burgers", category: "General" },
    { id: 1267, name: "25% Off", category: "Deals" },
    { id: 1218, name: "Crazy Deals", category: "Deals" },
    { id: 989, name: "Awesome Deals", category: "Deals" },
    { id: 121, name: "Budget", category: "General" },
    { id: 156, name: "Donuts", category: "General" },
    { id: 95, name: "Cakes", category: "Desserts" },
    { id: 99, name: "Crepes", category: "Desserts" },
    { id: 195, name: "Chocolates", category: "Desserts" },
  ],

  // Subpage tags (from the tree)
  subpageTags: [
    { id: 1, name: "Grills", category: "Subpage" },
    { id: 2, name: "Shawarma", category: "Subpage" },
    { id: 3, name: "Homestyle Meals", category: "Subpage" },
    { id: 4, name: "Manakish", category: "Subpage" },
    { id: 5, name: "Falafel", category: "Subpage" },
    { id: 6, name: "Sushi", category: "Subpage" },
    { id: 7, name: "Ramen", category: "Subpage" },
    { id: 8, name: "Dimsum", category: "Subpage" },
    { id: 9, name: "Pad Thai", category: "Subpage" },
    { id: 10, name: "Biryani", category: "Subpage" },
    { id: 11, name: "Chaat", category: "Subpage" },
    { id: 12, name: "Pizza", category: "Subpage" },
    { id: 13, name: "Pasta", category: "Subpage" },
    { id: 14, name: "Burger", category: "Subpage" },
    { id: 15, name: "BBQ & Grill", category: "Subpage" },
    { id: 16, name: "Breakfast", category: "Subpage" },
    { id: 17, name: "Tacos", category: "Subpage" },
    { id: 18, name: "Burritos", category: "Subpage" },
    { id: 19, name: "Kunafa", category: "Subpage" },
    { id: 20, name: "Mansaf", category: "Subpage" },
  ],
};
