const cuisineTagData = {
  cuisines: [
    {
      id: 1,
      name: "Lebanese",
      category: "Arabic",
      region: "",
      foodTags: ["Pie", "Mezze", "Manakish", "Kebab", "BBQ & Grill", "Hummus"],
      subpageTags: [],
    },
    {
      id: 2,
      name: "Syrian",
      category: "Arabic",
      region: "",
      foodTags: ["Foul", "Fatteh", "Kebab", "Tawooq", "Falafel", "Hummus"],
      subpageTags: [],
    },
    {
      id: 3,
      name: "Palestinian",
      category: "Arabic",
      region: "",
      foodTags: ["Fatteh", "Falafel", "Foul", "Tawooq", "Hummus"],
      subpageTags: [],
    },
    {
      id: 4,
      name: "Jordanian",
      category: "Arabic",
      region: "",
      foodTags: ["Mansaf (Jordanian)", "Kunafa"],
      subpageTags: [],
    },
    {
      id: 5,
      name: "Saudi",
      category: "Arabic",
      region: "",
      foodTags: ["Kabsa (Saudi)", "Mandi"],
      subpageTags: [],
    },
    {
      id: 6,
      name: "Emirati",
      category: "Arabic",
      region: "",
      foodTags: ["Lugaimat (Emirati)", "Harees (Emirati)"],
      subpageTags: [],
    },
    {
      id: 7,
      name: "Yemeni",
      category: "Arabic",
      region: "",
      foodTags: ["Biryani"],
      subpageTags: [],
    },
    {
      id: 8,
      name: "Kuwaiti",
      category: "Arabic",
      region: "",
      foodTags: ["Rice"],
      subpageTags: [],
    },
    {
      id: 9,
      name: "Egyptian",
      category: "Arabic",
      region: "",
      foodTags: ["Koshary (Egyptian)", "Mutabbaq"],
      subpageTags: [],
    },
    {
      id: 10,
      name: "Algerian",
      category: "Arabic",
      region: "",
      foodTags: ["Rice", "Meat Dish", "Chicken Dishes", "Tajin"],
      subpageTags: [],
    },
    {
      id: 11,
      name: "Moroccan",
      category: "Arabic",
      region: "",
      foodTags: ["Tajin"],
      subpageTags: [],
    },
    {
      id: 12,
      name: "Turkish",
      category: "Turkish",
      region: "",
      foodTags: ["Doner (Turkish)", "BBQ & Grill", "Kebab"],
      subpageTags: [],
    },
    {
      id: 13,
      name: "Japanese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Sushi",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 14,
      name: "Vietnamese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 15,
      name: "Thai",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 16,
      name: "Malaysian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 17,
      name: "Indonesian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Nasi Goreng (Indonesian)",
      ],
      subpageTags: [],
    },
    {
      id: 18,
      name: "Korean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Bibimbap (Korean)",
      ],
      subpageTags: [],
    },
    {
      id: 19,
      name: "Filipino",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 20,
      name: "Chinese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 21,
      name: "Singaporean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 22,
      name: "Nepali",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 23,
      name: "Sri Lankan",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 24,
      name: "Karahi",
      category: "Pakistani",
      region: "",
      foodTags: [
        "Handi",
        "Biryani",
        "Desi",
        "Chaat",
        "BBQ & Grill",
        "Kebab",
        "Paratha",
        "Chicken Dishes",
        "Curry Dishes",
        "Meat Dish",
      ],
      subpageTags: [],
    },
    {
      id: 25,
      name: "North Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 26,
      name: "Rajasthani",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 27,
      name: "Bengali",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 28,
      name: "Hyderabadi",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 29,
      name: "South Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Seafood",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 30,
      name: "Kerala",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 31,
      name: "Gujarati",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 32,
      name: "Goan",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 33,
      name: "Indo-Chinese (Limited used)",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 34,
      name: "Maharashtrian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 35,
      name: "Chettinad",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 36,
      name: "Sweets",
      category: "Desserts",
      region: "",
      foodTags: [
        "Crepes",
        "Shakes",
        "Ice Cream",
        "Frozen Yogurt",
        "Kulfi",
        "Chocolates",
        "Donuts",
        "Cookies",
        "Cakes",
        "Waffles",
      ],
      subpageTags: [],
    },
    {
      id: 37,
      name: "Healthy",
      category: "Healthy",
      region: "",
      foodTags: [
        "Desserts",
        "Soup",
        "Juices",
        "Bowls",
        "Breakfast",
        "Poke",
        "Protein Shake",
        "Poke",
        "Vegetarian",
        "Smoothies",
        "Salads",
        "Vegan",
        "Keto",
        "Gluten-free",
        "Acai",
        "Sandwiches and wraps",
        "Rolls",
        "Healthy Meals",
        "Healthy Salads",
        "Healthy Sandwiches",
        "Bagels",
        "Protein Balls",
        "Vegetarian",
      ],
      subpageTags: [],
    },
    {
      id: 38,
      name: "Cafe",
      category: "Cafe",
      region: "",
      foodTags: [
        "Breakfast",
        "Coffee",
        "Sandwiches",
        "Hot Beverages",
        "Bakery",
        "Sandwiches and wraps",
        "Sweets",
        "Juices",
        "Wraps",
        "Croissants",
        "Bakery & Confectionery",
        "Cocktails",
        "Sweets",
        "Juices",
        "Smoothies",
      ],
      subpageTags: [],
    },
    {
      id: 39,
      name: "Cafeteria",
      category: "Cafeteria",
      region: "",
      foodTags: [
        "Cocktails",
        "Wraps",
        "Sandwiches",
        "Juices",
        "Sandwiches and wraps",
        "Smoothies",
        "Snacks",
        "Street food",
        "Vitality Juices",
        "Breakfast",
        "Paratha (if the Cafeteria is Indian cuisine)",
        "Milk Shake",
      ],
      subpageTags: [],
    },
    {
      id: 40,
      name: "Burritos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 41,
      name: "Tacos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 42,
      name: "Pelmeni",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 43,
      name: "Borscht",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 44,
      name: "Russian Sushi",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 45,
      name: "French",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Croissants",
        "Bakery & Confectionery",
      ],
      subpageTags: [""],
    },
    {
      id: 46,
      name: "Greek",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Gyros",
        "Wraps",
        "Salads",
      ],
      subpageTags: [""],
    },
    {
      id: 47,
      name: "Portuguese",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Chicken",
      ],
      subpageTags: [""],
    },
    {
      id: 48,
      name: "German",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Doner",
        "Pretzel",
      ],
      subpageTags: [""],
    },
    {
      id: 49,
      name: "Spanish",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Tortilla",
      ],
      subpageTags: [""],
    },
    {
      id: 50,
      name: "British",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Fish & Chips",
        "Pie",
      ],
      subpageTags: [""],
    },
    {
      id: 51,
      name: "Scandinavian",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 52,
      name: "Italian",
      category: "European",
      region: "",
      foodTags: [
        "Pizza",
        "Pasta",
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [],
    },
    {
      id: 53,
      name: "Donuts",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 54,
      name: "Burger",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 55,
      name: "Brisket",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
  ],

  // All tags from active_tags.csv
  allTags: [
    {
      id: 1415,
      name: "Indo-Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1222, name: "0.1JOD DF", category: "Deals" },
    { id: 1248, name: "1 SAR", category: "Deals" },
    { id: 1828, name: "11:11 Sale", category: "Deals" },
    { id: 1857, name: "1st Weekend Dec", category: "Seasonal" },
    { id: 1518, name: "2024 Time Out award winners", category: "Awards" },
    { id: 1106, name: "20biryani", category: "Food" },
    { id: 1267, name: "25% Off", category: "Deals" },
    { id: 1336, name: "3 JODs", category: "Deals" },
    { id: 1237, name: "30% off BEST SELLER", category: "Deals" },
    { id: 1765, name: "3JODST1", category: "Deals" },
    { id: 1552, name: "50 OFF DESSERTS", category: "Deals" },
    { id: 366, name: "50% Off", category: "Deals" },
    { id: 757, name: "5SAR", category: "Deals" },
    { id: 1277, name: "5SAR - Breakfast", category: "Deals" },
    { id: 1278, name: "5SAR - Desserts", category: "Deals" },
    { id: 812, name: "Afghan", category: "Cuisine" },
    { id: 813, name: "African", category: "Cuisine" },
    { id: 1609, name: "American brands jo", category: "Brands" },
    { id: 815, name: "Asian", category: "Cuisine" },
    {
      id: 1390,
      name: "Arabic Sweets Desserts Tile Subpage",
      category: "Desserts",
    },
    { id: 596, name: "Arabic", category: "Cuisine" },
    { id: 426, name: "Arabic Coffee", category: "Beverages" },
    { id: 907, name: "Arabic Sweets", category: "Desserts" },
    { id: 1548, name: "Atayef", category: "Desserts" },
    { id: 1437, name: "AUH all resto", category: "Location" },
    { id: 989, name: "Awesome Deals", category: "Deals" },
    { id: 1174, name: "Bagels", category: "Breakfast" },
    { id: 211, name: "Bakery", category: "Food" },
    { id: 1258, name: "Bakery", category: "Food" },
    { id: 687, name: "Bakery & Confectionery", category: "Food" },
    { id: 42, name: "Bakery & Confectionery", category: "Food" },
    { id: 1467, name: "Bakery Tile Breakfast Subpage", category: "Breakfast" },
    { id: 1491, name: "Balkan", category: "Cuisine" },
    { id: 541, name: "BBQ & Grill", category: "Food" },
    { id: 163, name: "Beauty & Cosmetics", category: "Other" },
    { id: 360, name: "Beef", category: "Food" },
    { id: 1379, name: "Beef Burger Carousel Subpage", category: "Food" },
    { id: 97, name: "Biryani", category: "Food" },
    { id: 1754, name: "Biryani Large Orders", category: "Food" },
    { id: 1428, name: "Biryani Tile Indian Subpage", category: "Food" },
    { id: 1399, name: "Boba Tile Asian Subpage", category: "Asian" },
    { id: 685, name: "Bubble Tea", category: "Beverages" },
    { id: 121, name: "Budget", category: "General" },
    { id: 53, name: "Burger", category: "Food" },
    { id: 1755, name: "Burger Large orders", category: "Food" },
    { id: 223, name: "Burritos", category: "Food" },
    { id: 1770, name: "Butchery & Seafood", category: "Food" },
    { id: 1324, name: "Butter Chicken Campaign", category: "Seasonal" },
    { id: 1569, name: "C&D Ramadan", category: "Seasonal" },
    { id: 740, name: "Cabbage", category: "Vegetables" },
    { id: 817, name: "Cafe", category: "Beverage" },
    { id: 1310, name: "Caffeine Cravings", category: "Beverages" },
    { id: 95, name: "Cakes", category: "Desserts" },
    { id: 1391, name: "Cakes Desserts Tile Subpage", category: "Desserts" },
    { id: 818, name: "Canadian", category: "Cuisine" },
    { id: 300, name: "Candy", category: "Desserts" },
    { id: 1614, name: "Careem Choice", category: "General" },
    { id: 1612, name: "Carousel for Premium Users", category: "Premium" },
    { id: 1722, name: "Catering", category: "Service" },
    { id: 117, name: "Celebration", category: "Occasion" },
    { id: 1334, name: "Celebratory Sweets", category: "Desserts" },
    { id: 1072, name: "Chaat", category: "Food" },
    { id: 1427, name: "Chaat Tile Indian Subpage", category: "Food" },
    { id: 1322, name: "Cheat Day Special", category: "General" },
    { id: 1217, name: "Cheat Meal", category: "General" },
    { id: 113, name: "Chicken", category: "Food" },
    { id: 1753, name: "Chicken & Wings Large Orders", category: "Food" },
    { id: 1457, name: "Chicken & Wings Manual Carousel", category: "Food" },
    { id: 422, name: "Chicken Dishes", category: "Food" },
    { id: 763, name: "Chinese", category: "Cuisine" },
    {
      id: 1405,
      name: "Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1530, name: "Chocolate Valentine Offer Card", category: "Seasonal" },
    { id: 195, name: "Chocolates", category: "Desserts" },
    { id: 1513, name: "Christmas", category: "Seasonal" },
    { id: 1054, name: "Chucha Specials", category: "Deals" },
    { id: 1443, name: "Classic Burgers Subpage", category: "Food" },
    { id: 538, name: "Cocktails", category: "Beverages" },
    { id: 250, name: "Coffee", category: "Beverages" },
    { id: 1682, name: "Coffee & Desserts", category: "General" },
    { id: 90, name: "Coffee & Sweets", category: "General" },
    { id: 142, name: "Coffee Beans", category: "Beverages" },
    { id: 1314, name: "Coffee Lover", category: "General" },
    { id: 116, name: "Comfort", category: "General" },
    {
      id: 1527,
      name: "Comfort Food Valentine Offer Card",
      category: "Seasonal",
    },
    { id: 819, name: "Continental", category: "Cuisine" },
    { id: 820, name: "Cookies", category: "Desserts" },
    { id: 1388, name: "Cookies Desserts Tile Subpage", category: "Desserts" },
    { id: 485, name: "Cosmetics", category: "Other" },
    { id: 253, name: "Cosmetics", category: "Other" },
    { id: 620, name: "CPlus", category: "Premium" },
    { id: 1210, name: "CPlus Exclusive", category: "Premium" },
    { id: 1331, name: "CPlus Mondays", category: "Deals" },
    { id: 1218, name: "Crazy Deals", category: "Deals" },
    { id: 1597, name: "Crazy Deals Breakfast", category: "Deals" },
    { id: 1599, name: "Crazy Deals Dinner", category: "Deals" },
    { id: 1598, name: "Crazy Deals Lunch", category: "Deals" },
    { id: 99, name: "Crepes", category: "Desserts" },
    { id: 1047, name: "Croissants", category: "Breakfast" },
    { id: 463, name: "Curry Dishes", category: "Food" },
    { id: 139, name: "Daily Essentials", category: "General" },
    { id: 145, name: "Dairy & Eggs", category: "Food" },
    { id: 995, name: "Dairy Free", category: "Dietary" },
    { id: 1191, name: "Delivery Delay is Expected", category: "Info" },
    { id: 198, name: "Desi", category: "Food" },
    { id: 1558, name: "Desi Style Iftar", category: "Seasonal" },
    { id: 1559, name: "Desi Style Suhoor", category: "Seasonal" },
    { id: 1564, name: "Desi Sweets", category: "Desserts" },
    { id: 1357, name: "Dessert Brand Logos Subpage", category: "Desserts" },
    { id: 212, name: "Detox", category: "Healthy" },
    { id: 1142, name: "Dimsum", category: "Food" },
    { id: 1396, name: "Dimsums Tile Asian Subpage", category: "Asian" },
    { id: 1343, name: "Dinner for 2", category: "Occasion" },
    { id: 621, name: "Discounts", category: "Deals" },
    { id: 1231, name: "Diwali", category: "Seasonal" },
    { id: 821, name: "Doner", category: "Food" },
    { id: 156, name: "Donuts", category: "Desserts" },
    { id: 1385, name: "Donuts Desserts Tile Subpage", category: "Desserts" },
    { id: 1169, name: "Dosa", category: "Food" },
    { id: 1313, name: "Drinks Campaign", category: "Beverages" },
    { id: 1312, name: "Dummy Tag for Catalog", category: "Internal" },
    { id: 1147, name: "Dumpling", category: "Food" },
    { id: 1281, name: "Dunkin Donuts", category: "Brands" },
  ],

  // Subpage tags
  subpageTags: [
    { id: 1, name: "Grills", category: "Food" },
    { id: 2, name: "Shawarma", category: "Food" },
    { id: 3, name: "Manakish", category: "Food" },
    { id: 4, name: "Falafel", category: "Food" },
    { id: 5, name: "Kebab", category: "Food" },
    { id: 6, name: "Sushi", category: "Food" },
    { id: 7, name: "Ramen", category: "Food" },
    { id: 8, name: "Dimsum", category: "Food" },
    { id: 9, name: "Pad Thai", category: "Food" },
    { id: 10, name: "Biryani", category: "Food" },
    { id: 11, name: "Chaat", category: "Food" },
    { id: 12, name: "Pizza", category: "Food" },
    { id: 13, name: "Pasta", category: "Food" },
    { id: 14, name: "Burger", category: "Food" },
    { id: 15, name: "BBQ & Grill", category: "Food" },
    { id: 16, name: "Breakfast", category: "Food" },
    { id: 17, name: "Tacos", category: "Food" },
    { id: 18, name: "Burritos", category: "Food" },
    { id: 19, name: "Kunafa", category: "Desserts" },
    { id: 20, name: "Mansaf", category: "Food" },
    { id: 21, name: "Dosa", category: "Food" },
    { id: 22, name: "Idli", category: "Food" },
    { id: 23, name: "Coffee", category: "Beverages" },
    { id: 24, name: "Desserts", category: "Desserts" },
    { id: 25, name: "Wings", category: "Food" },
    { id: 26, name: "Fried Chicken", category: "Food" },
    { id: 27, name: "Fish & Chips", category: "Food" },
    { id: 28, name: "Steak", category: "Food" },
    { id: 29, name: "Salads", category: "Food" },
    { id: 30, name: "Vegetarian", category: "Dietary" },
    { id: 31, name: "Seafood", category: "Food" },
    { id: 32, name: "Poke", category: "Food" },
    { id: 33, name: "Bowls", category: "Food" },
    { id: 34, name: "Wraps", category: "Food" },
    { id: 35, name: "Sandwiches", category: "Food" },
    { id: 36, name: "Smoothies", category: "Beverages" },
    { id: 37, name: "Acai", category: "Desserts" },
    { id: 38, name: "Donuts", category: "Desserts" },
    { id: 39, name: "Cakes", category: "Desserts" },
    { id: 40, name: "Bakery", category: "Food" },
  ],
};


/* =========================
   AUTO-NORMALIZE IDs + OTHERS TAGS (from UAE Proposed Tree sheet)
   - Forces cuisine IDs to match sheet
   - Forces related tag IDs to match sheet
   - Adds "Others" as a TAG category (non-geographical cuisine tags)
   ========================= */
(() => {
  // Auto-map IDs from the provided sheet export (Name - ID)
  const nameToId = {
    "acai": 191,
    "acai tile subpage": 1366,
    "algerian": 1264,
    "american": 33,
    "arabic": 25,
    "arabic brand logos subpage": 1596,
    "arabic sweets desserts tile subpage": 1390,
    "artisanal pizza carousel subpage": 1358,
    "asian": 92,
    "asian brand logos subpage": 1351,
    "bagels": 1174,
    "bakery": 211,
    "bakery & confectionery": 42,
    "bakery tile breakfast subpage": 1467,
    "bbq & grill": 541,
    "beef burger carousel subpage": 1379,
    "bengali": 67,
    "bibimbap (korean)": 1153,
    "biryani": 97,
    "biryani tile indian subpage": 1428,
    "boba tile asian subpage": 1399,
    "boneless and wings subpage tag": 1459,
    "borscht": 1164,
    "bowls": 148,
    "bowls tile subpage": 1363,
    "breakfast": 124,
    "breakfast levant tile subpage": 1416,
    "breakfast subpage brand logos": 1448,
    "brisket": 1466,
    "brisket burger tile subpage": 1373,
    "british": 40,
    "bubble tea": 685,
    "burger": 53,
    "burger brand logos subpage": 1354,
    "burritos": 223,
    "cafe": 35,
    "cafeteria": 1179,
    "cakes": 95,
    "cakes desserts tile subpage": 1391,
    "chaat": 1072,
    "chaat tile indian subpage": 1427,
    "chettinad": 70,
    "chicken": 113,
    "chicken & wings large orders": 1753,
    "chicken & wings manual carousel": 1457,
    "chicken & wings subpage brand logos": 1449,
    "chicken burger carousel subpage": 1378,
    "chicken dishes": 422,
    "chicken sando burger tile subpage": 1372,
    "chinese": 1,
    "chinese moods carousel asian subpage": 1405,
    "chocolates": 195,
    "classic burgers subpage": 1443,
    "cocktails": 538,
    "coffee": 250,
    "coffee & desserts": 1682,
    "coffee & sweets": 90,
    "coffee breakfast subpage": 1456,
    "cookies": 820,
    "cookies desserts tile subpage": 1388,
    "crepes": 99,
    "croissant": 562,
    "croissants": 1047,
    "curry dishes": 463,
    "desi": 198,
    "dessert brand logos subpage": 1357,
    "desserts": 247,
    "desserts tile asian subpage": 1400,
    "dimsum": 1142,
    "dimsums tile asian subpage": 1396,
    "doner": 821,
    "doner (turkish)": 821,
    "donuts": 156,
    "donuts desserts tile subpage": 1385,
    "dosa": 1169,
    "dumplings": 762,
    "eggs & toast tile subpage": 1470,
    "egyptian": 39,
    "emirati": 47,
    "european": 2,
    "falafel": 243,
    "falafel levant tile subpage": 1410,
    "fast food": 659,
    "fatteh": 1412,
    "filipino": 41,
    "filipino moods carousel asian subpage": 1414,
    "fish": 394,
    "fish & chips": 656,
    "foul": 257,
    "foul & fatteh levant tile subpage": 1412,
    "french": 3,
    "fried chicken": 251,
    "fried rice tile asian subpage": 1401,
    "frozen yogurt": 249,
    "german": 38,
    "global chains burger tile subpage": 1377,
    "goan": 75,
    "gourmet burger tile subpage": 1374,
    "greek": 4,
    "grilled chicken subpage tag": 1460,
    "grilled tile healthy subpage": 1452,
    "grills levant tile subpage": 1383,
    "gujarati": 76,
    "gyros": 1165,
    "handi": 911,
    "harees (emirati)": 1143,
    "healthy": 544,
    "healthy brand logos subpage": 1355,
    "healthy breakfast subpage": 1454,
    "healthy desserts tile subpage": 1367,
    "healthy meals": 1885,
    "healthy salads": 1096,
    "healthy sandwiches": 1093,
    "homestyle meals levant tile subpage": 1382,
    "hot beverages": 464,
    "hot dog": 421,
    "hummus": 241,
    "hyderabadi": 78,
    "ice cream": 112,
    "ice cream desserts tile subpage": 1386,
    "indian": 5,
    "indian brand logos subpage": 1352,
    "indian sweets desserts tile subpage": 1392,
    "indonesian": 6,
    "italian": 8,
    "japanese": 9,
    "japanese moods carousel asian subpage": 1404,
    "jordanian": 46,
    "juices": 831,
    "kabsa (saudi)": 599,
    "karahi": 1904,
    "kebab": 847,
    "kerala": 79,
    "kerala tile indian subpage": 1430,
    "keto": 279,
    "keto tile subpage": 1368,
    "kids": 789,
    "korean": 10,
    "korean moods carousel asian subpage": 1406,
    "koshary (egyptian)": 725,
    "kulfi": 233,
    "kunafa": 202,
    "kunafa subpage tag": 1464,
    "kuwaiti": 57,
    "lebanese": 11,
    "levant brand logos subpage": 1356,
    "luqaimat": 454,
    "luqaimat (emirati)": 454,
    "maamoul": 1257,
    "maharashtrian": 80,
    "maki": 324,
    "malaysian": 27,
    "manakish": 414,
    "manakish levant tile subpage": 1384,
    "mandi": 598,
    "mansaf  (jordanian)": 1144,
    "matcha coffee subpage": 1653,
    "meals": 1154,
    "meat dish": 435,
    "mexican": 13,
    "mezze": 1895,
    "mezze levant tile subpage": 1411,
    "milk shake": 203,
    "milkshakes desserts tile subpage": 1389,
    "momos": 492,
    "moroccan": 14,
    "mutabbaq": 326,
    "nachos": 222,
    "nasi goreng (indonesian)": 1152,
    "nepali": 1279,
    "noodles": 490,
    "noodles & ramen": 151,
    "noodles tile asian subpage": 1398,
    "north indian": 83,
    "north indian subpage tile": 1421,
    "pad thai": 1145,
    "pakistani": 34,
    "palestinian": 1332,
    "pan asian": 357,
    "pancakes": 260,
    "pancit": 1149,
    "paratha": 679,
    "paratha (if the cafeteria is indian cuisine)": 679,
    "paratha tile indian subpage": 1425,
    "pasta": 106,
    "pastries": 153,
    "pelmeni": 1112,
    "petit four": 906,
    "pho": 1896,
    "pie": 375,
    "pizza": 54,
    "poke": 1899,
    "poke tile subpage": 1365,
    "popsicles": 917,
    "portuguese": 31,
    "pretzel": 1902,
    "protein balls": 452,
    "protein shake": 1168,
    "protein shakes tile subpage": 1364,
    "pure veg": 1074,
    "pure veg tile indian subpage": 1423,
    "quesadilla": 224,
    "rajasthani": 85,
    "ramen": 1349,
    "ramen tile asian subpage": 1397,
    "rest of asia moods carousel asian subpage": 1413,
    "rice": 349,
    "rolls": 229,
    "rolls tile indian subpage": 1431,
    "russian": 17,
    "russian sushi": 1664,
    "salads": 150,
    "salads tile subpage": 1361,
    "sandwiches": 147,
    "sandwiches  & wraps": 45,
    "sandwiches and wraps": 1173,
    "sandwiches breakfast subpage": 1453,
    "saudi": 207,
    "seafood": 600,
    "shakes": 236,
    "shawarma levant tile subpage": 1381,
    "sinagporean moods carousel asian subpage": 1408,
    "singaporean": 18,
    "sinigang": 1150,
    "sliders tile subpage": 1376,
    "smashed burger tile subpage": 1371,
    "smoothies": 259,
    "smoothies tile subpage": 1469,
    "snacks": 114,
    "soup": 149,
    "soups": 802,
    "south indian": 87,
    "south indian subpage tile": 1422,
    "spanish": 28,
    "sri lankan": 20,
    "steak": 839,
    "street food": 840,
    "sushi": 110,
    "sushi tile asian subpage": 1395,
    "sweets": 204,
    "sweets gifting options": 1435,
    "syrian": 44,
    "tacos": 225,
    "tajin": 352,
    "tapsilog": 1148,
    "tea": 401,
    "tea tile indian subpage": 1426,
    "thai": 21,
    "thai moods carousel asian subpage": 1403,
    "thali": 1073,
    "thali tile indian subpage": 1429,
    "tortilla": 1900,
    "turkish": 22,
    "turkish sweets": 1563,
    "value pizzas carousel subpage": 1359,
    "vegan": 682,
    "vegan burger tile subpage": 1375,
    "vegetarian": 808,
    "vietnamese": 23,
    "vietnamese moods carousel asian subpage": 1407,
    "vitality juices": 1091,
    "waffle fries": 392,
    "waffles": 325,
    "waffles & crepes desserts tile subpage": 1387,
    "wings": 273,
    "wraps": 469,
    "wraps tile subpage": 1362,
    "yemeni": 52
  };

  const norm = (s) => String(s || "").toLowerCase().trim();

  // 1) Force cuisine IDs to match the sheet exactly
  cuisineTagData.cuisines.forEach((c) => {
    const key = norm(c.name);
    if (nameToId[key]) c.id = nameToId[key];
  });

  // 2) Ensure every cuisine has foodTagIds (IDs) that match the sheet
  //    (we keep foodTags as display strings, but we derive IDs from the sheet mapping)
  cuisineTagData.cuisines.forEach((c) => {
    const ids = [];
    (c.foodTags || []).forEach((tagName) => {
      const id = nameToId[norm(tagName)];
      if (id) ids.push(id);
    });
    c.foodTagIds = Array.from(new Set(ids));
  });

  // 3) Add non-geographical tags under TAGS only (category: "Others")
  const nonGeoTags = [
  {
    "id": 802,
    "name": "Soups",
    "category": "Others"
  },
  {
    "id": 150,
    "name": "Salads",
    "category": "Others"
  },
  {
    "id": 259,
    "name": "Smoothies",
    "category": "Others"
  },
  {
    "id": 831,
    "name": "Juices",
    "category": "Others"
  },
  {
    "id": 204,
    "name": "Sweets",
    "category": "Others"
  },
  {
    "id": 147,
    "name": "Sandwiches",
    "category": "Others"
  },
  {
    "id": 112,
    "name": "Ice Cream",
    "category": "Others"
  },
  {
    "id": 113,
    "name": "Chicken",
    "category": "Others"
  },
  {
    "id": 250,
    "name": "Coffee",
    "category": "Others"
  },
  {
    "id": 247,
    "name": "Desserts",
    "category": "Others"
  },
  {
    "id": 251,
    "name": "Fried Chicken",
    "category": "Others"
  },
  {
    "id": 469,
    "name": "Wraps",
    "category": "Others"
  },
  {
    "id": 1169,
    "name": "Dosa",
    "category": "Others"
  },
  {
    "id": 401,
    "name": "Tea",
    "category": "Others"
  },
  {
    "id": 839,
    "name": "Steak",
    "category": "Others"
  },
  {
    "id": 375,
    "name": "Pie",
    "category": "Others"
  },
  {
    "id": 789,
    "name": "Kids",
    "category": "Others"
  },
  {
    "id": 53,
    "name": "Burger",
    "category": "Others"
  },
  {
    "id": 394,
    "name": "Fish",
    "category": "Others"
  },
  {
    "id": 273,
    "name": "Wings",
    "category": "Others"
  },
  {
    "id": 54,
    "name": "Pizza",
    "category": "Others"
  },
  {
    "id": 106,
    "name": "Pasta",
    "category": "Others"
  },
  {
    "id": 99,
    "name": "Crepes",
    "category": "Others"
  },
  {
    "id": 421,
    "name": "Hot Dog",
    "category": "Others"
  },
  {
    "id": 840,
    "name": "Street food",
    "category": "Others"
  },
  {
    "id": 42,
    "name": "Bakery & Confectionery",
    "category": "Others"
  },
  {
    "id": 95,
    "name": "Cakes",
    "category": "Others"
  },
  {
    "id": 35,
    "name": "cafe",
    "category": "Others"
  },
  {
    "id": 156,
    "name": "Donuts",
    "category": "Others"
  },
  {
    "id": 236,
    "name": "Shakes",
    "category": "Others"
  },
  {
    "id": 600,
    "name": "Seafood",
    "category": "Others"
  },
  {
    "id": 45,
    "name": "Sandwiches  & wraps",
    "category": "Others"
  },
  {
    "id": 820,
    "name": "Cookies",
    "category": "Others"
  },
  {
    "id": 659,
    "name": "fast food",
    "category": "Others"
  },
  {
    "id": 260,
    "name": "Pancakes",
    "category": "Others"
  },
  {
    "id": 325,
    "name": "Waffles",
    "category": "Others"
  },
  {
    "id": 1174,
    "name": "Bagels",
    "category": "Others"
  }
];
  cuisineTagData.allTags = cuisineTagData.allTags || [];
  const existingIds = new Set(cuisineTagData.allTags.map((t) => t && t.id));
  nonGeoTags.forEach((t) => {
    if (!existingIds.has(t.id)) {
      cuisineTagData.allTags.push(t);
      existingIds.add(t.id);
    }
  });
})();
