const cuisineTagData = {
  cuisines: [
    {
      id: 1,
      name: "Lebanese",
      category: "Arabic",
      region: "",
      foodTags: ["Pie", "Mezze", "Manakish", "Kebab", "BBQ & Grill", "Hummus"],
      subpageTags: [],
    },
    {
      id: 2,
      name: "Syrian",
      category: "Arabic",
      region: "",
      foodTags: ["Foul", "Fatteh", "Kebab", "Tawooq", "Falafel", "Hummus"],
      subpageTags: [],
    },
    {
      id: 3,
      name: "Palestinian",
      category: "Arabic",
      region: "",
      foodTags: ["Fatteh", "Falafel", "Foul", "Tawooq", "Hummus"],
      subpageTags: [],
    },
    {
      id: 4,
      name: "Jordanian",
      category: "Arabic",
      region: "",
      foodTags: ["Mansaf (Jordanian)", "Kunafa"],
      subpageTags: [],
    },
    {
      id: 5,
      name: "Saudi",
      category: "Arabic",
      region: "",
      foodTags: ["Kabsa (Saudi)", "Mandi"],
      subpageTags: [],
    },
    {
      id: 6,
      name: "Emirati",
      category: "Arabic",
      region: "",
      foodTags: ["Lugaimat (Emirati)", "Harees (Emirati)"],
      subpageTags: [],
    },
    {
      id: 7,
      name: "Yemeni",
      category: "Arabic",
      region: "",
      foodTags: ["Biryani"],
      subpageTags: [],
    },
    {
      id: 8,
      name: "Kuwaiti",
      category: "Arabic",
      region: "",
      foodTags: ["Rice"],
      subpageTags: [],
    },
    {
      id: 9,
      name: "Egyptian",
      category: "Arabic",
      region: "",
      foodTags: ["Koshary (Egyptian)", "Mutabbaq"],
      subpageTags: [],
    },
    {
      id: 10,
      name: "Algerian",
      category: "Arabic",
      region: "",
      foodTags: ["Rice", "Meat Dish", "Chicken Dishes", "Tajin"],
      subpageTags: [],
    },
    {
      id: 11,
      name: "Moroccan",
      category: "Arabic",
      region: "",
      foodTags: ["Tajin"],
      subpageTags: [],
    },
    {
      id: 12,
      name: "Turkish",
      category: "Turkish",
      region: "",
      foodTags: ["Doner (Turkish)", "BBQ & Grill", "Kebab"],
      subpageTags: [],
    },
    {
      id: 13,
      name: "Japanese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Sushi",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 14,
      name: "Vietnamese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 15,
      name: "Thai",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 16,
      name: "Malaysian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 17,
      name: "Indonesian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Nasi Goreng (Indonesian)",
      ],
      subpageTags: [],
    },
    {
      id: 18,
      name: "Korean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Bibimbap (Korean)",
      ],
      subpageTags: [],
    },
    {
      id: 19,
      name: "Filipino",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 20,
      name: "Chinese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 21,
      name: "Singaporean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 22,
      name: "Nepali",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 23,
      name: "Sri Lankan",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 24,
      name: "Karahi",
      category: "Pakistani",
      region: "",
      foodTags: [
        "Handi",
        "Biryani",
        "Desi",
        "Chaat",
        "BBQ & Grill",
        "Kebab",
        "Paratha",
        "Chicken Dishes",
        "Curry Dishes",
        "Meat Dish",
      ],
      subpageTags: [],
    },
    {
      id: 25,
      name: "North Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 26,
      name: "Rajasthani",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 27,
      name: "Bengali",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 28,
      name: "Hyderabadi",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 29,
      name: "South Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Seafood",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 30,
      name: "Kerala",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 31,
      name: "Gujarati",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 32,
      name: "Goan",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 33,
      name: "Indo-Chinese (Limited used)",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 34,
      name: "Maharashtrian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 35,
      name: "Chettinad",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 36,
      name: "Sweets",
      category: "Desserts",
      region: "",
      foodTags: [
        "Crepes",
        "Shakes",
        "Ice Cream",
        "Frozen Yogurt",
        "Kulfi",
        "Chocolates",
        "Donuts",
        "Cookies",
        "Cakes",
        "Waffles",
      ],
      subpageTags: [],
    },
    {
      id: 37,
      name: "Healthy",
      category: "Healthy",
      region: "",
      foodTags: [
        "Desserts",
        "Soup",
        "Juices",
        "Bowls",
        "Breakfast",
        "Poke",
        "Protein Shake",
        "Poke",
        "Vegetarian",
        "Smoothies",
        "Salads",
        "Vegan",
        "Keto",
        "Gluten-free",
        "Acai",
        "Sandwiches and wraps",
        "Rolls",
        "Healthy Meals",
        "Healthy Salads",
        "Healthy Sandwiches",
        "Bagels",
        "Protein Balls",
        "Vegetarian",
      ],
      subpageTags: [],
    },
    {
      id: 38,
      name: "Cafe",
      category: "Cafe",
      region: "",
      foodTags: [
        "Breakfast",
        "Coffee",
        "Sandwiches",
        "Hot Beverages",
        "Bakery",
        "Sandwiches and wraps",
        "Sweets",
        "Juices",
        "Wraps",
        "Croissants",
        "Bakery & Confectionery",
        "Cocktails",
        "Sweets",
        "Juices",
        "Smoothies",
      ],
      subpageTags: [],
    },
    {
      id: 39,
      name: "Cafeteria",
      category: "Cafeteria",
      region: "",
      foodTags: [
        "Cocktails",
        "Wraps",
        "Sandwiches",
        "Juices",
        "Sandwiches and wraps",
        "Smoothies",
        "Snacks",
        "Street food",
        "Vitality Juices",
        "Breakfast",
        "Paratha (if the Cafeteria is Indian cuisine)",
        "Milk Shake",
      ],
      subpageTags: [],
    },
    {
      id: 40,
      name: "Burritos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 41,
      name: "Tacos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 42,
      name: "Pelmeni",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 43,
      name: "Borscht",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 44,
      name: "Russian Sushi",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 45,
      name: "French",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Croissants",
        "Bakery & Confectionery",
      ],
      subpageTags: [""],
    },
    {
      id: 46,
      name: "Greek",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Gyros",
        "Wraps",
        "Salads",
      ],
      subpageTags: [""],
    },
    {
      id: 47,
      name: "Portuguese",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Chicken",
      ],
      subpageTags: [""],
    },
    {
      id: 48,
      name: "German",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Doner",
        "Pretzel",
      ],
      subpageTags: [""],
    },
    {
      id: 49,
      name: "Spanish",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Tortilla",
      ],
      subpageTags: [""],
    },
    {
      id: 50,
      name: "British",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Fish & Chips",
        "Pie",
      ],
      subpageTags: [""],
    },
    {
      id: 51,
      name: "Scandinavian",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 52,
      name: "Italian",
      category: "European",
      region: "",
      foodTags: [
        "Pizza",
        "Pasta",
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [],
    },
    {
      id: 53,
      name: "Donuts",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 54,
      name: "Burger",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 55,
      name: "Brisket",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
  ],

  // All tags from active_tags.csv
  allTags: [
    {
      id: 1415,
      name: "Indo-Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1222, name: "0.1JOD DF", category: "Deals" },
    { id: 1248, name: "1 SAR", category: "Deals" },
    { id: 1828, name: "11:11 Sale", category: "Deals" },
    { id: 1857, name: "1st Weekend Dec", category: "Seasonal" },
    { id: 1518, name: "2024 Time Out award winners", category: "Awards" },
    { id: 1106, name: "20biryani", category: "Food" },
    { id: 1267, name: "25% Off", category: "Deals" },
    { id: 1336, name: "3 JODs", category: "Deals" },
    { id: 1237, name: "30% off BEST SELLER", category: "Deals" },
    { id: 1765, name: "3JODST1", category: "Deals" },
    { id: 1552, name: "50 OFF DESSERTS", category: "Deals" },
    { id: 366, name: "50% Off", category: "Deals" },
    { id: 757, name: "5SAR", category: "Deals" },
    { id: 1277, name: "5SAR - Breakfast", category: "Deals" },
    { id: 1278, name: "5SAR - Desserts", category: "Deals" },
    { id: 812, name: "Afghan", category: "Cuisine" },
    { id: 813, name: "African", category: "Cuisine" },
    { id: 1609, name: "American brands jo", category: "Brands" },
    { id: 815, name: "Asian", category: "Cuisine" },
    {
      id: 1390,
      name: "Arabic Sweets Desserts Tile Subpage",
      category: "Desserts",
    },
    { id: 596, name: "Arabic", category: "Cuisine" },
    { id: 426, name: "Arabic Coffee", category: "Beverages" },
    { id: 907, name: "Arabic Sweets", category: "Desserts" },
    { id: 1548, name: "Atayef", category: "Desserts" },
    { id: 1437, name: "AUH all resto", category: "Location" },
    { id: 989, name: "Awesome Deals", category: "Deals" },
    { id: 1174, name: "Bagels", category: "Breakfast" },
    { id: 211, name: "Bakery", category: "Food" },
    { id: 1258, name: "Bakery", category: "Food" },
    { id: 687, name: "Bakery & Confectionery", category: "Food" },
    { id: 42, name: "Bakery & Confectionery", category: "Food" },
    { id: 1467, name: "Bakery Tile Breakfast Subpage", category: "Breakfast" },
    { id: 1491, name: "Balkan", category: "Cuisine" },
    { id: 541, name: "BBQ & Grill", category: "Food" },
    { id: 163, name: "Beauty & Cosmetics", category: "Other" },
    { id: 360, name: "Beef", category: "Food" },
    { id: 1379, name: "Beef Burger Carousel Subpage", category: "Food" },
    { id: 97, name: "Biryani", category: "Food" },
    { id: 1754, name: "Biryani Large Orders", category: "Food" },
    { id: 1428, name: "Biryani Tile Indian Subpage", category: "Food" },
    { id: 1399, name: "Boba Tile Asian Subpage", category: "Asian" },
    { id: 685, name: "Bubble Tea", category: "Beverages" },
    { id: 121, name: "Budget", category: "General" },
    { id: 53, name: "Burger", category: "Food" },
    { id: 1755, name: "Burger Large orders", category: "Food" },
    { id: 223, name: "Burritos", category: "Food" },
    { id: 1770, name: "Butchery & Seafood", category: "Food" },
    { id: 1324, name: "Butter Chicken Campaign", category: "Seasonal" },
    { id: 1569, name: "C&D Ramadan", category: "Seasonal" },
    { id: 740, name: "Cabbage", category: "Vegetables" },
    { id: 817, name: "Cafe", category: "Beverage" },
    { id: 1310, name: "Caffeine Cravings", category: "Beverages" },
    { id: 95, name: "Cakes", category: "Desserts" },
    { id: 1391, name: "Cakes Desserts Tile Subpage", category: "Desserts" },
    { id: 818, name: "Canadian", category: "Cuisine" },
    { id: 300, name: "Candy", category: "Desserts" },
    { id: 1614, name: "Careem Choice", category: "General" },
    { id: 1612, name: "Carousel for Premium Users", category: "Premium" },
    { id: 1722, name: "Catering", category: "Service" },
    { id: 117, name: "Celebration", category: "Occasion" },
    { id: 1334, name: "Celebratory Sweets", category: "Desserts" },
    { id: 1072, name: "Chaat", category: "Food" },
    { id: 1427, name: "Chaat Tile Indian Subpage", category: "Food" },
    { id: 1322, name: "Cheat Day Special", category: "General" },
    { id: 1217, name: "Cheat Meal", category: "General" },
    { id: 113, name: "Chicken", category: "Food" },
    { id: 1753, name: "Chicken & Wings Large Orders", category: "Food" },
    { id: 1457, name: "Chicken & Wings Manual Carousel", category: "Food" },
    { id: 422, name: "Chicken Dishes", category: "Food" },
    { id: 763, name: "Chinese", category: "Cuisine" },
    {
      id: 1405,
      name: "Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1530, name: "Chocolate Valentine Offer Card", category: "Seasonal" },
    { id: 195, name: "Chocolates", category: "Desserts" },
    { id: 1513, name: "Christmas", category: "Seasonal" },
    { id: 1054, name: "Chucha Specials", category: "Deals" },
    { id: 1443, name: "Classic Burgers Subpage", category: "Food" },
    { id: 538, name: "Cocktails", category: "Beverages" },
    { id: 250, name: "Coffee", category: "Beverages" },
    { id: 1682, name: "Coffee & Desserts", category: "General" },
    { id: 90, name: "Coffee & Sweets", category: "General" },
    { id: 142, name: "Coffee Beans", category: "Beverages" },
    { id: 1314, name: "Coffee Lover", category: "General" },
    { id: 116, name: "Comfort", category: "General" },
    {
      id: 1527,
      name: "Comfort Food Valentine Offer Card",
      category: "Seasonal",
    },
    { id: 819, name: "Continental", category: "Cuisine" },
    { id: 820, name: "Cookies", category: "Desserts" },
    { id: 1388, name: "Cookies Desserts Tile Subpage", category: "Desserts" },
    { id: 485, name: "Cosmetics", category: "Other" },
    { id: 253, name: "Cosmetics", category: "Other" },
    { id: 620, name: "CPlus", category: "Premium" },
    { id: 1210, name: "CPlus Exclusive", category: "Premium" },
    { id: 1331, name: "CPlus Mondays", category: "Deals" },
    { id: 1218, name: "Crazy Deals", category: "Deals" },
    { id: 1597, name: "Crazy Deals Breakfast", category: "Deals" },
    { id: 1599, name: "Crazy Deals Dinner", category: "Deals" },
    { id: 1598, name: "Crazy Deals Lunch", category: "Deals" },
    { id: 99, name: "Crepes", category: "Desserts" },
    { id: 1047, name: "Croissants", category: "Breakfast" },
    { id: 463, name: "Curry Dishes", category: "Food" },
    { id: 139, name: "Daily Essentials", category: "General" },
    { id: 145, name: "Dairy & Eggs", category: "Food" },
    { id: 995, name: "Dairy Free", category: "Dietary" },
    { id: 1191, name: "Delivery Delay is Expected", category: "Info" },
    { id: 198, name: "Desi", category: "Food" },
    { id: 1558, name: "Desi Style Iftar", category: "Seasonal" },
    { id: 1559, name: "Desi Style Suhoor", category: "Seasonal" },
    { id: 1564, name: "Desi Sweets", category: "Desserts" },
    { id: 1357, name: "Dessert Brand Logos Subpage", category: "Desserts" },
    { id: 212, name: "Detox", category: "Healthy" },
    { id: 1142, name: "Dimsum", category: "Food" },
    { id: 1396, name: "Dimsums Tile Asian Subpage", category: "Asian" },
    { id: 1343, name: "Dinner for 2", category: "Occasion" },
    { id: 621, name: "Discounts", category: "Deals" },
    { id: 1231, name: "Diwali", category: "Seasonal" },
    { id: 821, name: "Doner", category: "Food" },
    { id: 156, name: "Donuts", category: "Desserts" },
    { id: 1385, name: "Donuts Desserts Tile Subpage", category: "Desserts" },
    { id: 1169, name: "Dosa", category: "Food" },
    { id: 1313, name: "Drinks Campaign", category: "Beverages" },
    { id: 1312, name: "Dummy Tag for Catalog", category: "Internal" },
    { id: 1147, name: "Dumpling", category: "Food" },
    { id: 1281, name: "Dunkin Donuts", category: "Brands" },
  ],

  // Subpage tags
  subpageTags: [
    { id: 1, name: "Grills", category: "Food" },
    { id: 2, name: "Shawarma", category: "Food" },
    { id: 3, name: "Manakish", category: "Food" },
    { id: 4, name: "Falafel", category: "Food" },
    { id: 5, name: "Kebab", category: "Food" },
    { id: 6, name: "Sushi", category: "Food" },
    { id: 7, name: "Ramen", category: "Food" },
    { id: 8, name: "Dimsum", category: "Food" },
    { id: 9, name: "Pad Thai", category: "Food" },
    { id: 10, name: "Biryani", category: "Food" },
    { id: 11, name: "Chaat", category: "Food" },
    { id: 12, name: "Pizza", category: "Food" },
    { id: 13, name: "Pasta", category: "Food" },
    { id: 14, name: "Burger", category: "Food" },
    { id: 15, name: "BBQ & Grill", category: "Food" },
    { id: 16, name: "Breakfast", category: "Food" },
    { id: 17, name: "Tacos", category: "Food" },
    { id: 18, name: "Burritos", category: "Food" },
    { id: 19, name: "Kunafa", category: "Desserts" },
    { id: 20, name: "Mansaf", category: "Food" },
    { id: 21, name: "Dosa", category: "Food" },
    { id: 22, name: "Idli", category: "Food" },
    { id: 23, name: "Coffee", category: "Beverages" },
    { id: 24, name: "Desserts", category: "Desserts" },
    { id: 25, name: "Wings", category: "Food" },
    { id: 26, name: "Fried Chicken", category: "Food" },
    { id: 27, name: "Fish & Chips", category: "Food" },
    { id: 28, name: "Steak", category: "Food" },
    { id: 29, name: "Salads", category: "Food" },
    { id: 30, name: "Vegetarian", category: "Dietary" },
    { id: 31, name: "Seafood", category: "Food" },
    { id: 32, name: "Poke", category: "Food" },
    { id: 33, name: "Bowls", category: "Food" },
    { id: 34, name: "Wraps", category: "Food" },
    { id: 35, name: "Sandwiches", category: "Food" },
    { id: 36, name: "Smoothies", category: "Beverages" },
    { id: 37, name: "Acai", category: "Desserts" },
    { id: 38, name: "Donuts", category: "Desserts" },
    { id: 39, name: "Cakes", category: "Desserts" },
    { id: 40, name: "Bakery", category: "Food" },
  ],
};


/* =========================
   AUTO-NORMALIZE IDs + OTHERS TAGS (from UAE Proposed Tree sheet)
   - Forces cuisine IDs to match sheet
   - Forces related tag IDs to match sheet
   - Adds "Others" as a TAG category (non-geographical cuisine tags)
   ========================= */
(() => {
  // Maps are LOWERCASED keys
  const cuisineIdByName = {
  "lebanese": 11,
  "syrian": 44,
  "palestinian": 1332,
  "jordanian": 46,
  "saudi": 207,
  "emirati": 47,
  "yemeni": 52,
  "kuwaiti": 57,
  "egyptian": 39,
  "algerian": 1264,
  "moroccan": 14,
  "turkish": 22,
  "japanese": 9,
  "vietnamese": 23,
  "thai": 21,
  "malaysian": 27,
  "indonesian": 6,
  "korean": 10,
  "filipino": 41,
  "chinese": 1,
  "singaporean": 18,
  "nepali": 1279,
  "sri lankan": 20,
  "karahi": 1904,
  "north indian": 83,
  "rajasthani": 85,
  "bengali": 67,
  "hyderabadi": 78,
  "south indian": 87,
  "kerala": 79,
  "gujarati": 76,
  "goan": 75,
  "indo-chinese (limited used)": 1177,
  "maharashtrian": 80,
  "chettinad": 70,
  "sweets": 348,
  "italian": 8,
  "french": 3,
  "greek": 4,
  "portuguese": 31,
  "german": 38,
  "spanish": 28,
  "british": 40,
  "american": 33
};
  const cuisineCategoryByName = {
  "lebanese": "Arabic",
  "syrian": "Arabic",
  "palestinian": "Arabic",
  "jordanian": "Arabic",
  "saudi": "Arabic",
  "emirati": "Arabic",
  "yemeni": "Arabic",
  "kuwaiti": "Arabic",
  "egyptian": "Arabic",
  "algerian": "Arabic",
  "moroccan": "Arabic",
  "turkish": "Arabic",
  "japanese": "Asian",
  "vietnamese": "Asian",
  "thai": "Asian",
  "malaysian": "Asian",
  "indonesian": "Asian",
  "korean": "Asian",
  "filipino": "Asian",
  "chinese": "Asian",
  "singaporean": "Asian",
  "nepali": "Asian",
  "sri lankan": "Asian",
  "karahi": "Pakistani",
  "north indian": "Indian",
  "rajasthani": "Indian",
  "bengali": "Indian",
  "hyderabadi": "Indian",
  "south indian": "Indian",
  "kerala": "Indian",
  "gujarati": "Indian",
  "goan": "Indian",
  "indo-chinese (limited used)": "Indian",
  "maharashtrian": "Indian",
  "chettinad": "Indian",
  "sweets": "Desserts",
  "italian": "European",
  "french": "European",
  "greek": "European",
  "portuguese": "European",
  "german": "European",
  "spanish": "European",
  "british": "European",
  "american": "American"
};
  const tagIdByName = {
  "pie": 375,
  "manakish": 414,
  "pastries": 153,
  "levant brand logos subpage": 1356,
  "breakfast": 124,
  "foul": 257,
  "mezze": 1895,
  "kebab": 847,
  "bbq & grill": 541,
  "breakfast levant tile subpage": 1416,
  "bakery": 211,
  "fatteh": 1412,
  "falafel": 243,
  "hummus": 241,
  "falafel levant tile subpage": 1410,
  "mansaf  (jordanian)": 1144,
  "kunafa": 202,
  "foul & fatteh levant tile subpage": 1412,
  "kabsa (saudi)": 599,
  "mandi": 598,
  "grills levant tile subpage": 1383,
  "luqaimat (emirati)": 454,
  "harees (emirati)": 1143,
  "homestyle meals levant tile subpage": 1382,
  "biryani": 97,
  "manakish levant tile subpage": 1384,
  "rice": 349,
  "mezze levant tile subpage": 1411,
  "koshary (egyptian)": 725,
  "mutabbaq": 326,
  "shawarma levant tile subpage": 1381,
  "arabic sweets desserts tile subpage": 1390,
  "tajin": 352,
  "arabic brand logos subpage": 1596,
  "doner (turkish)": 821,
  "grilled chicken subpage tag": 1460,
  "dimsum": 1142,
  "sinigang": 1150,
  "indo-chinese moods carousel asian subpage": 1415,
  "pad thai": 1145,
  "noodles": 490,
  "chinese moods carousel asian subpage": 1405,
  "sweets": 204,
  "sushi": 110,
  "ramen": 1349,
  "filipino moods carousel asian subpage": 1414,
  "vegetarian": 808,
  "pho": 1896,
  "noodles & ramen": 151,
  "japanese moods carousel asian subpage": 1404,
  "seafood": 600,
  "dumplings": 762,
  "nasi goreng (indonesian)": 1152,
  "korean moods carousel asian subpage": 1406,
  "bubble tea": 685,
  "bibimbap (korean)": 1153,
  "rest of asia moods carousel asian subpage": 1413,
  "poke": 1899,
  "tapsilog": 1148,
  "sinagporean moods carousel asian subpage": 1408,
  "pan asian": 357,
  "pancit": 1149,
  "thai moods carousel asian subpage": 1403,
  "maki": 324,
  "vietnamese moods carousel asian subpage": 1407,
  "asian brand logos subpage": 1351,
  "boba tile asian subpage": 1399,
  "handi": 911,
  "desi": 198,
  "indian brand logos subpage": 1352,
  "biryani tile indian subpage": 1428,
  "kulfi": 233,
  "chaat tile indian subpage": 1427,
  "pure veg": 1074,
  "chaat": 1072,
  "kerala tile indian subpage": 1430,
  "momos": 492,
  "north indian subpage tile": 1421,
  "thali": 1073,
  "paratha tile indian subpage": 1425,
  "paratha": 679,
  "pure veg tile indian subpage": 1423,
  "rolls tile indian subpage": 1431,
  "meals": 1154,
  "meat dish": 435,
  "south indian subpage tile": 1422,
  "chicken dishes": 422,
  "tea tile indian subpage": 1426,
  "snacks": 114,
  "curry dishes": 463,
  "thali tile indian subpage": 1429,
  "soup": 149,
  "gujarati": 1897,
  "salads": 150,
  "crepes": 99,
  "dessert brand logos subpage": 1357,
  "artisanal pizza carousel subpage": 1358,
  "bakery & confectionery": 42,
  "croissant": 562,
  "gyros": 1165,
  "wraps": 469,
  "chicken": 113,
  "doner": 821,
  "pretzel": 1902,
  "tortilla": 1900,
  "fish & chips": 656,
  "burger": 53,
  "chicken & wings manual carousel": 1457,
  "fried chicken": 251
};

  const nonGeographicalTags = [
  {
    "id": 802,
    "name": "Soups",
    "category": "Others"
  },
  {
    "id": 665,
    "name": "Salads",
    "category": "Others"
  },
  {
    "id": 331,
    "name": "Smoothies",
    "category": "Others"
  },
  {
    "id": 102,
    "name": "Juices",
    "category": "Others"
  },
  {
    "id": 348,
    "name": "Sweets",
    "category": "Others"
  },
  {
    "id": 508,
    "name": "Sandwiches",
    "category": "Others"
  },
  {
    "id": 248,
    "name": "Ice Cream",
    "category": "Others"
  },
  {
    "id": 777,
    "name": "Chicken",
    "category": "Others"
  },
  {
    "id": 507,
    "name": "Coffee",
    "category": "Others"
  },
  {
    "id": 247,
    "name": "Desserts",
    "category": "Others"
  },
  {
    "id": 346,
    "name": "Fried Chicken",
    "category": "Others"
  },
  {
    "id": 470,
    "name": "Wraps",
    "category": "Others"
  },
  {
    "id": 1906,
    "name": "Dosa",
    "category": "Others"
  },
  {
    "id": 401,
    "name": "Tea",
    "category": "Others"
  },
  {
    "id": 109,
    "name": "Steak",
    "category": "Others"
  },
  {
    "id": 796,
    "name": "Pie",
    "category": "Others"
  },
  {
    "id": 789,
    "name": "Kids",
    "category": "Others"
  },
  {
    "id": 844,
    "name": "Burger",
    "category": "Others"
  },
  {
    "id": 394,
    "name": "Fish",
    "category": "Others"
  },
  {
    "id": 811,
    "name": "Wings",
    "category": "Others"
  },
  {
    "id": 313,
    "name": "Pizza",
    "category": "Others"
  },
  {
    "id": 794,
    "name": "Pasta",
    "category": "Others"
  },
  {
    "id": 780,
    "name": "Crepes",
    "category": "Others"
  },
  {
    "id": 786,
    "name": "Hot Dog",
    "category": "Others"
  },
  {
    "id": 88,
    "name": "Street food",
    "category": "Others"
  },
  {
    "id": 687,
    "name": "Bakery & Confectionery",
    "category": "Others"
  },
  {
    "id": 765,
    "name": "Cakes",
    "category": "Others"
  },
  {
    "id": 248,
    "name": "Ice Cream",
    "category": "Others"
  },
  {
    "id": 35,
    "name": "cafe",
    "category": "Others"
  },
  {
    "id": 761,
    "name": "Donuts",
    "category": "Others"
  },
  {
    "id": 811,
    "name": "Wings",
    "category": "Others"
  },
  {
    "id": 438,
    "name": "Shakes",
    "category": "Others"
  },
  {
    "id": 507,
    "name": "Coffee",
    "category": "Others"
  },
  {
    "id": 24,
    "name": "Seafood",
    "category": "Others"
  },
  {
    "id": 45,
    "name": "Sandwiches  & wraps",
    "category": "Others"
  },
  {
    "id": 201,
    "name": "Cookies",
    "category": "Others"
  },
  {
    "id": 36,
    "name": "fast food",
    "category": "Others"
  },
  {
    "id": 1907,
    "name": "Pancakes",
    "category": "Others"
  },
  {
    "id": 200,
    "name": "Waffles",
    "category": "Others"
  },
  {
    "id": 1908,
    "name": "Bagels",
    "category": "Others"
  }
];

  const normKey = (s) =>
    String(s || "")
      .toLowerCase()
      .trim()
      // remove "(...)" suffix in names like "Mansaf (Jordanian)"
      .replace(/\s*\([^\)]*\)\s*/g, " ")
      .replace(/\s+/g, " ")
      .trim();

  // Ensure arrays exist
  cuisineTagData.cuisines = Array.isArray(cuisineTagData.cuisines) ? cuisineTagData.cuisines.filter(Boolean) : [];
  // Remove any accidental 'Others' cuisine (Others should live under TAGS only)
  cuisineTagData.cuisines = cuisineTagData.cuisines.filter((c) => normKey(c?.name) !== "others");
  cuisineTagData.allTags = Array.isArray(cuisineTagData.allTags) ? cuisineTagData.allTags.filter(Boolean) : [];

  // 1) Force cuisine IDs + (optionally) category names to match sheet
  cuisineTagData.cuisines.forEach((c) => {
    const key = normKey(c.name);
    if (cuisineIdByName[key]) c.id = cuisineIdByName[key];
    if (cuisineCategoryByName[key]) c.category = cuisineCategoryByName[key];
  });

  // 2) Add non-geographical tags into allTags under category "Others"
  const existingTagIds = new Set(cuisineTagData.allTags.map((t) => t && t.id));
  nonGeographicalTags.forEach((t) => {
    if (!existingTagIds.has(t.id)) {
      cuisineTagData.allTags.push({
        id: t.id,
        name: t.name,
        category: "Others",
      });
      existingTagIds.add(t.id);
    }
  });

  // 3) Ensure any sheet-defined tags (food/subpage/general) exist in allTags with correct IDs
  Object.entries(tagIdByName).forEach(([nameKey, id]) => {
    if (!existingTagIds.has(id)) {
      // Try to keep a reasonable category if it already exists by name
      const existingByName = cuisineTagData.allTags.find((t) => normKey(t.name) === nameKey);
      cuisineTagData.allTags.push({
        id,
        name: existingByName ? existingByName.name : nameKey,
        category: (existingByName && existingByName.category) ? existingByName.category : "Food",
      });
      existingTagIds.add(id);
    }
  });

  // 4) Convert cuisine.foodTags from names -> tag IDs (for reliable lookups + exact IDs)
  cuisineTagData.cuisines.forEach((c) => {
    const converted = [];
    (c.foodTags || []).forEach((tagName) => {
      const k = normKey(tagName);
      const id = tagIdByName[k];
      if (id) converted.push(id);
    });
    c.foodTagIds = converted; // new field used by the app
  });
})();

