const cuisineTagData = {
  cuisines: [
    {
      id: 37,
      name: "Lebanese",
      category: "Arabic",
      region: "",
      foodTags: ["Pie", "Mezze", "Manakish", "Kebab", "BBQ & Grill", "Hummus"],
      subpageTags: [],
    },
    {
      id: 59,
      name: "Syrian",
      category: "Arabic",
      region: "",
      foodTags: ["Foul", "Fatteh", "Kebab", "Tawooq", "Falafel", "Hummus"],
      subpageTags: [],
    },
    {
      id: 1264,
      name: "Palestinian",
      category: "Arabic",
      region: "",
      foodTags: ["Fatteh", "Falafel", "Foul", "Tawooq", "Hummus"],
      subpageTags: [],     
    },
    {
      id: 1265,
      name: "Jordanian",
      category: "Arabic",
      region: "",
      foodTags: ["Mansaf (Jordanian)", "Kunafa"],
      subpageTags: [],  
    },
    {
      id: 1266,
      name: "Saudi",
      category: "Arabic",
      region: "",
      foodTags: ["Kabsa (Saudi)", "Mandi"],
      subpageTags: [],  
    },
    {
      id: 1267,
      name: "Emirati",
      category: "Arabic",
      region: "",
      foodTags: ["Lugaimat (Emirati)", "Harees (Emirati)"],
      subpageTags: [],
    },
    {
      id: 1268,
      name: "Yemeni",
      category: "Arabic",
      region: "",
      foodTags: ["Biryani"],
      subpageTags: [],  
    },
    {
      id: 1269,
      name: "Kuwaiti",
      category: "Arabic",
      region: "",
      foodTags: ["Rice"],
      subpageTags: [],
    },
    {
      id: 1270,
      name: "Egyptian",
      category: "Arabic",
      region: "",
      foodTags: ["Koshary (Egyptian)", "Mutabbaq"],
      subpageTags: [],
    },
    {
      id: 1271,
      name: "Algerian",
      category: "Arabic",
      region: "",
      foodTags: ["Rice", "Meat Dish", "Chicken Dishes", "Tajin"],
      subpageTags: [],
    },
    {
      id: 1272,
      name: "Moroccan",
      category: "Arabic",
      region: "",
      foodTags: ["Tajin"],
      subpageTags: [],
    },
    {
      id: 1273,
      name: "Turkish",
      category: "Turkish",
      region: "",
      foodTags: ["Doner (Turkish)", "BBQ & Grill", "Kebab"],
      subpageTags: [],
    },
    {
      id: 1,
      name: "Japanese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Sushi",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },

    {
      id: 2,
      name: "Vietnamese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 3,
      name: "Thai",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 4,
      name: "Malaysian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 5,
      name: "Indonesian",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Nasi Goreng (Indonesian)",
      ],
      subpageTags: [],
    },
    {
      id: 6,
      name: "Korean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
        "Bibimbap (Korean)",
      ],
      subpageTags: [],
    },
    {
      id: 7,
      name: "Filipino",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 8,
      name: "Chinese",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 9,
      name: "Singaporean",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 10,
      name: "Nepali",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 11,
      name: "Sri Lankan",
      category: "Asian",
      region: "",
      foodTags: [
        "Dimsum",
        "Sinigang",
        "Noodles",
        "Ramen",
        "Bubble Tea",
        "Pad Thai",
        "Pho",
        "Noodles & Ramen",
        "Dumplings",
        "Tapsilog",
        "Pancit",
        "Seafood",
      ],
      subpageTags: [],
    },
    {
      id: 12,
      name: "Karahi",
      category: "Pakistani",
      region: "",
      foodTags: [
        "Handi",
        "Biryani",
        "Desi",
        "Chaat",
        "BBQ & Grill",
        "Kebab",
        "Paratha",
        "Chicken Dishes",
        "Curry Dishes",
        "Meat Dish",
      ],
      subpageTags: [],
    },
    {
      id: 13,
      name: "North Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 14,
      name: "Rajasthani",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 15,
      name: "Bengali",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 16,
      name: "Hyderabadi",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 17,
      name: "South Indian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Seafood",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 18,
      name: "Kerala",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 19,
      name: "Gujarati",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 20,
      name: "Goan",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 21,
      name: "Indo-Chinese (Limited used)",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 22,
      name: "Maharashtrian",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Meals",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 23,
      name: "Chettinad",
      category: "Indian",
      region: "",
      foodTags: [
        "Kebab",
        "Kulfi",
        "Chaat",
        "Momos",
        "Biryani",
        "Paratha",
        "BBQ & Grill",
        "Meat Dish",
        "Chicken Dishes",
        "Curry Dishes",
        "Gujarati",
        "Pure Veg",
        "Thali",
        "Vegetarian",
        "Dosa",
        "Desi",
      ],
      subpageTags: [],
    },
    {
      id: 26,
      name: "Sweets",
      category: "Desserts",
      region: "",
      foodTags: [
        "Crepes",
        "Shakes",
        "Ice Cream",
        "Frozen Yogurt",
        "Kulfi",
        "Chocolates",
        "Donuts",
        "Cookies",
        "Cakes",
        "Waffles",
      ],
      subpageTags: [],
    },
    {},
    {
      id: 34,
      name: "Healthy",
      category: "Healthy",
      region: "",
      foodTags: [
        "Desserts",
        "Soup",
        "Juices",
        "Bowls",
        "Breakfast",
        "Poke",
        "Protein Shake",
        "Poke",
        "Vegetarian",
        "Smoothies",
        "Salads",
        "Vegan",
        "Keto",
        "Gluten-free",
        "Acai",
        "Sandwiches and wraps",
        "Rolls",
        "Healthy Meals",
        "Healthy Salads",
        "Healthy Sandwiches",
        "Bagels",
        "Protein Balls",
        "Vegetarian",
      ],
      subpageTags: [],
    },
    {
      id: 36,
      name: "Cafe",
      category: "Cafe",
      region: "",
      foodTags: [
        "Breakfast",
        "Coffee",
        "Sandwiches",
        "Hot Beverages",
        "Bakery",
        "Sandwiches and wraps",
        "Sweets",
        "Juices",
        "Wraps",
        "Croissants",
        "Bakery & Confectionery",
        "Cocktails",
        "Sweets",
        "Juices",
        "Smoothies",
      ],
      subpageTags: [],
    },
    {
      id: 38,
      name: "Cafeteria",
      category: "Cafeteria",
      region: "",
      foodTags: [
        "Cocktails",
        "Wraps",
        "Sandwiches",
        "Juices",
        "Sandwiches and wraps",
        "Smoothies",
        "Snacks",
        "Street food",
        "Vitality Juices",
        "Breakfast",
        "Paratha (if the Cafeteria is Indian cuisine)",
        "Milk Shake",
      ],
      subpageTags: [],
    },
    {
      id: 41,
      name: "Burritos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 42,
      name: "Tacos",
      category: "Mexican",
      region: "",
      foodTags: ["Quesadilla", "Nachos"],
      subpageTags: [""],
    },
    {
      id: 43,
      name: "Pelmeni",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 44,
      name: "Borscht",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 44,
      name: "Russian Sushi",
      category: "Russian",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 45,
      name: "French",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Croissants",
        "Bakery & Confectionery",
      ],
      subpageTags: [""],
    },
    {
      id: 46,
      name: "Greek",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Gyros",
        "Wraps",
        "Salads",
      ],
      subpageTags: [""],
    },
    {
      id: 46,
      name: "Portuguese",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Chicken",
      ],
      subpageTags: [""],
    },
    {
      id: 47,
      name: "German",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Doner",
        "Pretzel",
      ],
      subpageTags: [""],
    },
    {
      id: 48,
      name: "Spanish",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Tortilla",
      ],
      subpageTags: [""],
    },
    {
      id: 49,
      name: "British",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
        "Fish & Chips",
        "Pie",
      ],
      subpageTags: [""],
    },
    {
      id: 50,
      name: "Scandinavian",
      category: "European",
      region: "",
      foodTags: [
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [""],
    },
    {
      id: 51,
      name: "Italian",
      category: "European",
      region: "",
      foodTags: [
        "Pizza",
        "Pasta",
        "Seafood",
        "Breakfast",
        "BBQ & Grill",
        "Desserts",
        "Vegetarian",
        "Bakery",
        "Pastries",
      ],
      subpageTags: [],
    },
    {
      id: 52,
      name: "Donuts",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 53,
      name: "Burger",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
    {
      id: 53,
      name: "Brisket",
      category: "American",
      region: "",
      foodTags: [
        "Fast Food",
        "Nachos",
        "Waffle Fries",
        "Burger",
        "Hot Dog",
        "Wings",
        "Steak",
      ],
      subpageTags: [],
    },
  ],

  // All tags from active_tags.csv
  allTags: [
    {
      id: 1415,
      name: "Indo-Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1222, name: "0.1JOD DF", category: "Deals" },
    { id: 1248, name: "1 SAR", category: "Deals" },
    { id: 1828, name: "11:11 Sale", category: "Deals" },
    { id: 1857, name: "1st Weekend Dec", category: "Seasonal" },
    { id: 1518, name: "2024 Time Out award winners", category: "Awards" },
    { id: 1106, name: "20biryani", category: "Food" },
    { id: 1267, name: "25% Off", category: "Deals" },
    { id: 1336, name: "3 JODs", category: "Deals" },
    { id: 1237, name: "30% off BEST SELLER", category: "Deals" },
    { id: 1765, name: "3JODST1", category: "Deals" },
    { id: 1552, name: "50 OFF DESSERTS", category: "Deals" },
    { id: 366, name: "50% Off", category: "Deals" },
    { id: 757, name: "5SAR", category: "Deals" },
    { id: 1277, name: "5SAR - Breakfast", category: "Deals" },
    { id: 1278, name: "5SAR - Desserts", category: "Deals" },
    { id: 812, name: "Afghan", category: "Cuisine" },
    { id: 813, name: "African", category: "Cuisine" },
    { id: 1609, name: "American brands jo", category: "Brands" },
    { id: 815, name: "Asian", category: "Cuisine" },
    {
      id: 1390,
      name: "Arabic Sweets Desserts Tile Subpage",
      category: "Desserts",
    },
    { id: 596, name: "Arabic", category: "Cuisine" },
    { id: 426, name: "Arabic Coffee", category: "Beverages" },
    { id: 907, name: "Arabic Sweets", category: "Desserts" },
    { id: 1548, name: "Atayef", category: "Desserts" },
    { id: 1437, name: "AUH all resto", category: "Location" },
    { id: 989, name: "Awesome Deals", category: "Deals" },
    { id: 1174, name: "Bagels", category: "Breakfast" },
    { id: 211, name: "Bakery", category: "Food" },
    { id: 1258, name: "Bakery", category: "Food" },
    { id: 687, name: "Bakery & Confectionery", category: "Food" },
    { id: 42, name: "Bakery & Confectionery", category: "Food" },
    { id: 1467, name: "Bakery Tile Breakfast Subpage", category: "Breakfast" },
    { id: 1491, name: "Balkan", category: "Cuisine" },
    { id: 541, name: "BBQ & Grill", category: "Food" },
    { id: 163, name: "Beauty & Cosmetics", category: "Other" },
    { id: 360, name: "Beef", category: "Food" },
    { id: 1379, name: "Beef Burger Carousel Subpage", category: "Food" },
    { id: 97, name: "Biryani", category: "Food" },
    { id: 1754, name: "Biryani Large Orders", category: "Food" },
    { id: 1428, name: "Biryani Tile Indian Subpage", category: "Food" },
    { id: 1399, name: "Boba Tile Asian Subpage", category: "Asian" },
    { id: 685, name: "Bubble Tea", category: "Beverages" },
    { id: 121, name: "Budget", category: "General" },
    { id: 53, name: "Burger", category: "Food" },
    { id: 1755, name: "Burger Large orders", category: "Food" },
    { id: 223, name: "Burritos", category: "Food" },
    { id: 1770, name: "Butchery & Seafood", category: "Food" },
    { id: 1324, name: "Butter Chicken Campaign", category: "Seasonal" },
    { id: 1569, name: "C&D Ramadan", category: "Seasonal" },
    { id: 740, name: "Cabbage", category: "Vegetables" },
    { id: 817, name: "Cafe", category: "Beverage" },
    { id: 1310, name: "Caffeine Cravings", category: "Beverages" },
    { id: 95, name: "Cakes", category: "Desserts" },
    { id: 1391, name: "Cakes Desserts Tile Subpage", category: "Desserts" },
    { id: 818, name: "Canadian", category: "Cuisine" },
    { id: 300, name: "Candy", category: "Desserts" },
    { id: 1614, name: "Careem Choice", category: "General" },
    { id: 1612, name: "Carousel for Premium Users", category: "Premium" },
    { id: 1722, name: "Catering", category: "Service" },
    { id: 117, name: "Celebration", category: "Occasion" },
    { id: 1334, name: "Celebratory Sweets", category: "Desserts" },
    { id: 1072, name: "Chaat", category: "Food" },
    { id: 1427, name: "Chaat Tile Indian Subpage", category: "Food" },
    { id: 1322, name: "Cheat Day Special", category: "General" },
    { id: 1217, name: "Cheat Meal", category: "General" },
    { id: 113, name: "Chicken", category: "Food" },
    { id: 1753, name: "Chicken & Wings Large Orders", category: "Food" },
    { id: 1457, name: "Chicken & Wings Manual Carousel", category: "Food" },
    { id: 422, name: "Chicken Dishes", category: "Food" },
    { id: 763, name: "Chinese", category: "Cuisine" },
    {
      id: 1405,
      name: "Chinese Moods Carousel Asian Subpage",
      category: "Asian",
    },
    { id: 1530, name: "Chocolate Valentine Offer Card", category: "Seasonal" },
    { id: 195, name: "Chocolates", category: "Desserts" },
    { id: 1513, name: "Christmas", category: "Seasonal" },
    { id: 1054, name: "Chucha Specials", category: "Deals" },
    { id: 1443, name: "Classic Burgers Subpage", category: "Food" },
    { id: 538, name: "Cocktails", category: "Beverages" },
    { id: 250, name: "Coffee", category: "Beverages" },
    { id: 1682, name: "Coffee & Desserts", category: "General" },
    { id: 90, name: "Coffee & Sweets", category: "General" },
    { id: 142, name: "Coffee Beans", category: "Beverages" },
    { id: 1314, name: "Coffee Lover", category: "General" },
    { id: 116, name: "Comfort", category: "General" },
    {
      id: 1527,
      name: "Comfort Food Valentine Offer Card",
      category: "Seasonal",
    },
    { id: 819, name: "Continental", category: "Cuisine" },
    { id: 820, name: "Cookies", category: "Desserts" },
    { id: 1388, name: "Cookies Desserts Tile Subpage", category: "Desserts" },
    { id: 485, name: "Cosmetics", category: "Other" },
    { id: 253, name: "Cosmetics", category: "Other" },
    { id: 620, name: "CPlus", category: "Premium" },
    { id: 1210, name: "CPlus Exclusive", category: "Premium" },
    { id: 1331, name: "CPlus Mondays", category: "Deals" },
    { id: 1218, name: "Crazy Deals", category: "Deals" },
    { id: 1597, name: "Crazy Deals Breakfast", category: "Deals" },
    { id: 1599, name: "Crazy Deals Dinner", category: "Deals" },
    { id: 1598, name: "Crazy Deals Lunch", category: "Deals" },
    { id: 99, name: "Crepes", category: "Desserts" },
    { id: 1047, name: "Croissants", category: "Breakfast" },
    { id: 463, name: "Curry Dishes", category: "Food" },
    { id: 139, name: "Daily Essentials", category: "General" },
    { id: 145, name: "Dairy & Eggs", category: "Food" },
    { id: 995, name: "Dairy Free", category: "Dietary" },
    { id: 1191, name: "Delivery Delay is Expected", category: "Info" },
    { id: 198, name: "Desi", category: "Food" },
    { id: 1558, name: "Desi Style Iftar", category: "Seasonal" },
    { id: 1559, name: "Desi Style Suhoor", category: "Seasonal" },
    { id: 1564, name: "Desi Sweets", category: "Desserts" },
    { id: 1357, name: "Dessert Brand Logos Subpage", category: "Desserts" },
    { id: 212, name: "Detox", category: "Healthy" },
    { id: 1142, name: "Dimsum", category: "Food" },
    { id: 1396, name: "Dimsums Tile Asian Subpage", category: "Asian" },
    { id: 1343, name: "Dinner for 2", category: "Occasion" },
    { id: 621, name: "Discounts", category: "Deals" },
    { id: 1231, name: "Diwali", category: "Seasonal" },
    { id: 821, name: "Doner", category: "Food" },
    { id: 156, name: "Donuts", category: "Desserts" },
    { id: 1385, name: "Donuts Desserts Tile Subpage", category: "Desserts" },
    { id: 1169, name: "Dosa", category: "Food" },
    { id: 1313, name: "Drinks Campaign", category: "Beverages" },
    { id: 1312, name: "Dummy Tag for Catalog", category: "Internal" },
    { id: 1147, name: "Dumpling", category: "Food" },
    { id: 1281, name: "Dunkin Donuts", category: "Brands" },
  ],

  // Subpage tags
  subpageTags: [
    { id: 1, name: "Grills", category: "Food" },
    { id: 2, name: "Shawarma", category: "Food" },
    { id: 3, name: "Manakish", category: "Food" },
    { id: 4, name: "Falafel", category: "Food" },
    { id: 5, name: "Kebab", category: "Food" },
    { id: 6, name: "Sushi", category: "Food" },
    { id: 7, name: "Ramen", category: "Food" },
    { id: 8, name: "Dimsum", category: "Food" },
    { id: 9, name: "Pad Thai", category: "Food" },
    { id: 10, name: "Biryani", category: "Food" },
    { id: 11, name: "Chaat", category: "Food" },
    { id: 12, name: "Pizza", category: "Food" },
    { id: 13, name: "Pasta", category: "Food" },
    { id: 14, name: "Burger", category: "Food" },
    { id: 15, name: "BBQ & Grill", category: "Food" },
    { id: 16, name: "Breakfast", category: "Food" },
    { id: 17, name: "Tacos", category: "Food" },
    { id: 18, name: "Burritos", category: "Food" },
    { id: 19, name: "Kunafa", category: "Desserts" },
    { id: 20, name: "Mansaf", category: "Food" },
    { id: 21, name: "Dosa", category: "Food" },
    { id: 22, name: "Idli", category: "Food" },
    { id: 23, name: "Coffee", category: "Beverages" },
    { id: 24, name: "Desserts", category: "Desserts" },
    { id: 25, name: "Wings", category: "Food" },
    { id: 26, name: "Fried Chicken", category: "Food" },
    { id: 27, name: "Fish & Chips", category: "Food" },
    { id: 28, name: "Steak", category: "Food" },
    { id: 29, name: "Salads", category: "Food" },
    { id: 30, name: "Vegetarian", category: "Dietary" },
    { id: 31, name: "Seafood", category: "Food" },
    { id: 32, name: "Poke", category: "Food" },
    { id: 33, name: "Bowls", category: "Food" },
    { id: 34, name: "Wraps", category: "Food" },
    { id: 35, name: "Sandwiches", category: "Food" },
    { id: 36, name: "Smoothies", category: "Beverages" },
    { id: 37, name: "Acai", category: "Desserts" },
    { id: 38, name: "Donuts", category: "Desserts" },
    { id: 39, name: "Cakes", category: "Desserts" },
    { id: 40, name: "Bakery", category: "Food" },
  ],

  // Subpage tags array
  subpageTags: [
    { id: 1001, name: "Levant Brand Logos Subpage", category: "Subpage" },
    { id: 1002, name: "Breakfast Levant Tile Subpage", category: "Subpage" },
    { id: 1003, name: "Falafel Levant Tile Subpage", category: "Subpage" },
    {
      id: 1004,
      name: "Foul & Fatteh Levant Tile Subpage",
      category: "Subpage",
    },
    { id: 1005, name: "Grills Levant Tile Subpage", category: "Subpage" },
    {
      id: 1006,
      name: "Homestyle Meals Levant Tile Subpage",
      category: "Subpage",
    },
    { id: 1007, name: "Manakish Levant Tile Subpage", category: "Subpage" },
    { id: 1008, name: "Mezze Levant Tile Subpage", category: "Subpage" },
    { id: 1009, name: "Shawarma Levant Tile Subpage", category: "Subpage" },
    {
      id: 1010,
      name: "Arabic Sweets Desserts Tile Subpage",
      category: "Subpage",
    },
    {
      id: 1011,
      name: "Indo-Chinese Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1012,
      name: "Chinese Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1013,
      name: "Filipino Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1014,
      name: "Japanese Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1015,
      name: "Korean Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1016,
      name: "Rest of Asia Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1017,
      name: "Sinagporean Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1018,
      name: "Thai Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    {
      id: 1019,
      name: "Vietnamese Moods Carousel Asian Subpage",
      category: "Subpage",
    },
    { id: 1020, name: "Asian Brand Logos Subpage", category: "Subpage" },
    { id: 1021, name: "Boba Tile Asian Subpage", category: "Subpage" },
    { id: 1022, name: "Desserts Tile Asian Subpage", category: "Subpage" },
    { id: 1023, name: "Dimsums Tile Asian Subpage", category: "Subpage" },
    { id: 1024, name: "Fried Rice Tile Asian Subpage", category: "Subpage" },
    { id: 1025, name: "Noodles Tile Asian Subpage", category: "Subpage" },
    { id: 1026, name: "Ramen Tile Asian Subpage", category: "Subpage" },
    { id: 1027, name: "Sushi Tile Asian Subpage", category: "Subpage" },
    { id: 1028, name: "Dessert Brand Logos Subpage", category: "Subpage" },
    { id: 1029, name: "Cakes Desserts Tile Subpage", category: "Subpage" },
    { id: 1030, name: "Cookies Desserts Tile Subpage", category: "Subpage" },
    { id: 1031, name: "Donuts Desserts Tile Subpage", category: "Subpage" },
    { id: 1032, name: "Ice Cream Desserts Tile Subpage", category: "Subpage" },
    {
      id: 1033,
      name: "Indian Sweets Desserts Tile Subpage",
      category: "Subpage",
    },
    { id: 1034, name: "Milkshakes Desserts Tile Subpage", category: "Subpage" },
    {
      id: 1035,
      name: "Waffles & Crepes Desserts Tile Subpage",
      category: "Subpage",
    },
    { id: 1036, name: "Guilt-free desserts", category: "Subpage" },
    { id: 1037, name: "Gifting options", category: "Subpage" },
    { id: 1038, name: "Kunafa Subpage Tag", category: "Subpage" },
    { id: 1039, name: "Indian Brand Logos Subpage", category: "Subpage" },
    { id: 1040, name: "Biryani Tile Indian Subpage", category: "Subpage" },
    { id: 1041, name: "Chaat Tile Indian Subpage", category: "Subpage" },
    { id: 1042, name: "keralai Tile Indian Subpage", category: "Subpage" },
    { id: 1043, name: "North Indian Subpage Tile Indian", category: "Subpage" },
    { id: 1044, name: "Paratha Tile Indian Subpage", category: "Subpage" },
    { id: 1045, name: "Pure Veg Tile Indian Subpage", category: "Subpage" },
    { id: 1046, name: "Rolls Tile Indian Subpage", category: "Subpage" },
    { id: 1047, name: "South Indian Subpage Tile", category: "Subpage" },
    { id: 1048, name: "Tea Tile Indian Subpage", category: "Subpage" },
    { id: 1049, name: "Thali Tile Indian Subpage", category: "Subpage" },
    { id: 1050, name: "Healthy Brand Logos Subpage", category: "Subpage" },
    { id: 1051, name: "Healthy Desserts Tile Subpage", category: "Subpage" },
    { id: 1052, name: "Grilled Tile Healthy Subpage", category: "Subpage" },
    { id: 1053, name: "Salads Tile Healthy Subpage", category: "Subpage" },
    { id: 1054, name: "Bowls Tile Healthy Subpage", category: "Subpage" },
    { id: 1055, name: "Poke Tile Healthy Subpage", category: "Subpage" },
    { id: 1056, name: "Acai Tile Subpage", category: "Subpage" },
    { id: 1057, name: "Keto Tile Subpage", category: "Subpage" },
    { id: 1058, name: "Vegan Burger Tile Subpage", category: "Subpage" },
    { id: 1059, name: "Protein Shakes Tile Subpage", category: "Subpage" },
    { id: 1060, name: "Healthy Breakfast Subpage", category: "Subpage" },
    { id: 1061, name: "Sugar-free Subpage Tag", category: "Subpage" },
    { id: 1062, name: "Bakery Tile Breakfast Subpage", category: "Subpage" },
    { id: 1063, name: "Coffee & Desserts", category: "Subpage" },
    { id: 1064, name: "Coffee & Sweets", category: "Subpage" },
    { id: 1065, name: "Eggs & Toast Tile Subpage", category: "Subpage" },
    { id: 1066, name: "Coffee Breakfast Subpage", category: "Subpage" },
    { id: 1067, name: "Breakfast Subpage Brand Logos", category: "Subpage" },
    { id: 1068, name: "Sandwiches Breakfast Subpage", category: "Subpage" },
    { id: 1069, name: "Matcha Coffee Subpage", category: "Subpage" },
    { id: 1070, name: "Smoothies Tile Subpage", category: "Subpage" },
    { id: 1071, name: "Wraps Tile Subpage", category: "Subpage" },
    { id: 1072, name: "SSandwiches Breakfast Subpage", category: "Subpage" },
    { id: 1073, name: "Artisanal Pizza Carousel Subpage", category: "Subpage" },
    { id: 1074, name: "Value Pizzas Carousel Subpage", category: "Subpage" },
    { id: 1075, name: "Brisket Burger Tile Subpage", category: "Subpage" },
    { id: 1076, name: "Chicken & Wings Large Orders", category: "Subpage" },
    { id: 1077, name: "Chicken & Wings Manual Carousel", category: "Subpage" },
    {
      id: 1078,
      name: "Chicken & Wings Subpage Brand Logos",
      category: "Subpage",
    },
    { id: 1079, name: "Boneless and wings Subpage Tag", category: "Subpage" },
    { id: 1080, name: "Burger Brand Logos Subpage", category: "Subpage" },
    { id: 1081, name: "Beef Burger Carousel Subpage", category: "Subpage" },
    { id: 1082, name: "Chicken Burger Carousel Subpage", category: "Subpage" },
    { id: 1083, name: "Brisket Burger Tile Subpage", category: "Subpage" },
    {
      id: 1084,
      name: "Chicken Sando Burger Tile Subpage",
      category: "Subpage",
    },
    {
      id: 1085,
      name: "Global Chains Burger Tile Subpage",
      category: "Subpage",
    },
    { id: 1086, name: "Gourmet Burger Tile Subpage", category: "Subpage" },
    { id: 1087, name: "Smashed Burger Tile Subpage", category: "Subpage" },
    { id: 1088, name: "Sliders Tile Subpage", category: "Subpage" },
    { id: 1089, name: "Classic Burgers Subpage", category: "Subpage" },
  ],
};

